(function () {
    var modules = {
        "panel-main-shq-astn": { url: "$A/components/panel/panel-main-shq.html"},
        "panel-child-shq-astn": { url: "$A/components/panel/panel-child-shq.html" },

        "project-shq-data": {
            url: "$A/components/project/project-shq-data.html", Table: "astn-shq-project-20003481", form_module: "project-shq-form", router: 1,
            child_panel: "panel-main-shq-astn"
        },
        "project-shq-form": { url: "$A/components/project/project-shq-form.html", Table: "astn-shq-project-20003481" },

        "participant-shq-data": {
            url: "$A/components/participant/participant-shq-data.html", Table: "astn-shq-participant-20002391", form_module: "participant-shq-form",
            child_panel: "panel-child-shq-astn",
            questionnaire_setup: "online-questionnaire-setup-shq-astn",
            online_questionnaire: "online-questionnaire-app-shq-astn",
            participant_id: { field1: "Local_ID", field2: "Initials" }
        },
        "participant-shq-form": { url: "$A/components/participant/participant-shq-form.html", Table: "astn-shq-participant-20002391" },

        "online-questionnaire-setup-shq-astn": { url: "$A/online-questionnaire/components/online-questionnaire-setup.html", Table: "astn-shq-participant-20002391" },
        "online-questionnaire-app-shq-astn": { url: "$A/online-questionnaire/index.html" },

        "notes": { url: "$B/mdb/n/notes.html" },

        "consent-astn-data": { url: "$B/mdb/c/consent-astn-data.html", Table: "consent-astn-20002423", form_module: "consent-astn-form" },
        "consent-astn-form": { url: "$B/mdb/c/consent-astn-form.html", Table: "consent-astn-20002423", task_name:"Consent" },
        "background-information-astn-data": { url: "$B/mdb/b/background-information-astn-data.html", Table: "background-information-astn-20002400", form_module: "background-information-astn-form" },
        "background-information-astn-form": { url: "$B/mdb/b/background-information-astn-form.html", Table: "background-information-astn-20002400", task_name:"Background Information" },
        "general-astn-data": { url: "$B/mdb/g/general-astn-data.html", Table: "general-astn-20002401", form_module: "general-astn-form" },
        "general-astn-form": { url: "$B/mdb/g/general-astn-form.html", Table: "general-astn-20002401", task_name:"General" },
        "ethnicity-self-astn-data": { url: "$B/mdb/e/ethnicity-self-astn-data.html", Table: "ethnicity-self-astn-20002402", form_module: "ethnicity-self-astn-form" },
        "ethnicity-self-astn-form": { url: "$B/mdb/e/ethnicity-self-astn-form.html", Table: "ethnicity-self-astn-20002402", task_name:"Ethnicity" },
        "lifestyle-astn-data": { url: "$B/mdb/l/lifestyle-astn-data.html", Table: "lifestyle-astn-20002403", form_module: "lifestyle-astn-form" },
        "lifestyle-astn-form": { url: "$B/mdb/l/lifestyle-astn-form.html", Table: "lifestyle-astn-20002403", task_name:"Lifestyle" },
        "medical-history-astn-data": { url: "$B/mdb/m/medical-history-astn-data.html", Table: "medical-history-astn-20002404", form_module: "medical-history-astn-form" },
        "medical-history-astn-form": { url: "$B/mdb/m/medical-history-astn-form.html", Table: "medical-history-astn-20002404", task_name:"Medical_History" },
        "sleep-disorder-patterns-astn-data": { url: "$B/mdb/s/sleep-disorder-patterns-astn-data.html", Table: "sleep-disorder-patterns-astn-20002405", form_module: "sleep-disorder-patterns-astn-form" },
        "sleep-disorder-patterns-astn-form": { url: "$B/mdb/s/sleep-disorder-patterns-astn-form.html", Table: "sleep-disorder-patterns-astn-20002405", task_name:"Sleep HQDP" },
        "sleep-hygiene-index-astn-data": { url: "$B/mdb/s/sleep-hygiene-index-astn-data.html", Table: "sleep-hygiene-index-astn-20003571", form_module: "sleep-hygiene-index-astn-form" },
        "sleep-hygiene-index-astn-form": { url: "$B/mdb/s/sleep-hygiene-index-astn-form.html", Table: "sleep-hygiene-index-astn-20003571", task_name:"Sleep Hygiene Index" },
        "social-history-astn-data": { url: "$B/mdb/s/social-history-astn-data.html", Table: "social-history-astn-20002406", form_module: "social-history-astn-form" },
        "social-history-astn-form": { url: "$B/mdb/s/social-history-astn-form.html", Table: "social-history-astn-20002406", task_name:"Family Sleep History" },
        "medications-astn-data": { url: "$B/mdb/m/medications-astn-data.html", Table: "medications-astn-20002407", form_module: "medications-astn-form" },
        "medications-astn-form": { url: "$B/mdb/m/medications-astn-form.html", Table: "medications-astn-20002407", task_name:"Medications" },
        "rec-drug-astn-data": { url: "$B/mdb/r/rec-drug-astn-data.html", Table: "rec-drug-astn-20003574", form_module: "rec-drug-astn-form" },
        "rec-drug-astn-form": { url: "$B/mdb/r/rec-drug-astn-form.html", Table: "rec-drug-astn-20003574", task_name:"Recreational Drugs" },
        "ess-astn-data": { url: "$B/mdb/e/ess-astn-data.html", Table: "ess-astn-20002408", form_module: "ess-astn-form" },
        "ess-astn-form": { url: "$B/mdb/e/ess-astn-form.html", Table: "ess-astn-20002408", task_name:"Epworth Sleepiness Scale" },
        "map-astn-data": { url: "$B/mdb/m/map-astn-data.html", Table: "map-astn-20002409", form_module: "map-astn-form" },
        "map-astn-form": { url: "$B/mdb/m/map-astn-form.html", Table: "map-astn-20002409", task_name:"Multivariate Apnea Prediction Questionnaire" },
        "isi-astn-data": { url: "$B/mdb/i/isi-astn-data.html", Table: "isi-astn-20002410", form_module: "isi-astn-form" },
        "isi-astn-form": { url: "$B/mdb/i/isi-astn-form.html", Table: "isi-astn-20002410", task_name:"Insomnia Severity Index" },
        "restless-leg-astn-data": { url: "$B/mdb/r/restless-leg-astn-data.html", Table: "restless-leg-astn-20002411", form_module: "restless-leg-astn-form" },
        "restless-leg-astn-form": { url: "$B/mdb/r/restless-leg-astn-form.html", Table: "restless-leg-astn-20002411", task_name:"Restless Legs" },
        "me-astn-data": { url: "$B/mdb/m/me-astn-data.html", Table: "me-astn-20002412", form_module: "me-astn-form" },
        "me-astn-form": { url: "$B/mdb/m/me-astn-form.html", Table: "me-astn-20002412", task_name:"Horne & &#214;stberg Morningness-Eveningness Composite Questionnaire" },
        "fosq-astn-data": { url: "$B/mdb/f/fosq-astn-data.html", Table: "fosq-astn-20002413", form_module: "fosq-astn-form" },
        "fosq-astn-form": { url: "$B/mdb/f/fosq-astn-form.html", Table: "fosq-astn-20002413", task_name:"Functional Outcomes of Sleep Questionnaire" },
        "psqi-astn-data": { url: "$B/mdb/p/psqi-astn-data.html", Table: "psqi-astn-20003576", form_module: "psqi-astn-form" },
        "psqi-astn-form": { url: "$B/mdb/p/psqi-astn-form.html", Table: "psqi-ast-20003576", task_name:"Pittsburgh Sleep Quality Index" },
        "phq-astn-data": { url: "$B/mdb/p/phq-astn-data.html", Table: "phq-astn-20002414", form_module: "phq-astn-form" },
        "phq-astn-form": { url: "$B/mdb/p/phq-astn-form.html", Table: "phq-astn-20002414", task_name:"Patient Health Questionnaire (PHQ-9)" },
        "gad7-astn-data": { url: "$B/mdb/g/gad7-astn-data.html", Table: "gad7-astn-20002415", form_module: "gad7-astn-form" },
        "gad7-astn-form": { url: "$B/mdb/g/gad7-astn-form.html", Table: "gad7-astn-20002415", task_name:"Generalised Anxiety Disorder (GAD-7)" },
        "dass-astn-data": { url: "$B/mdb/d/dass-astn-data.html", Table: "dass-astn-20002416", form_module: "dass-astn-form" },
        "dass-astn-form": { url: "$B/mdb/d/dass-astn-form.html", Table: "dass-astn-20002416", task_name:"Depression Anxiety Stress Scale (DASS-21)" },
        "fss-astn-data": { url: "$B/mdb/f/fss-astn-data.html", Table: "fss-astn-20002417", form_module: "fss-astn-form" },
        "fss-astn-form": { url: "$B/mdb/f/fss-astn-form.html", Table: "fss-astn-20002417", task_name:"Fatigue Severity Scale (FSS)" },
        "sds-astn-data": { url: "$B/mdb/s/sds-astn-data.html", Table: "sds-astn-20002418", form_module: "sds-astn-form" },
        "sds-astn-form": { url: "$B/mdb/s/sds-astn-form.html", Table: "sds-astn-20002418", task_name:"Sheehan Disability Scale (SDS)" },
        "hwpq-astn-data": { url: "$B/mdb/h/hwpq-astn-data.html", Table: "hwpq-astn-20002419", form_module: "hwpq-astn-form" },
        "hwpq-astn-form": { url: "$B/mdb/h/hwpq-astn-form.html", Table: "hwpq-astn-20002419", task_name:"Health & Work Performance Questionnaire" },
        "shiftwork-astn-data": { url: "$B/mdb/s/shiftwork-astn-data.html", Table: "shiftwork-astn-20002420", form_module: "shiftwork-astn-form" },
        "shiftwork-astn-form": { url: "$B/mdb/s/shiftwork-astn-form.html", Table: "shiftwork-astn-20002420", task_name:"Shiftwork" },
        "shiftworkii-astn-data": { url: "$B/mdb/s/shiftworkii-astn-data.html", Table: "shiftworkii-astn-20003584", form_module: "shiftworkii-astn-form" },
        "shiftworkii-astn-form": { url: "$B/mdb/s/shiftworkii-astn-form.html", Table: "shiftworkii-astn-20003584", task_name:"Shiftwork II" },
        "mva-astn-data": { url: "$B/mdb/m/mva-astn-data.html", Table: "mva-astn-20002421", form_module: "mva-astn-form" },
        "mva-astn-form": { url: "$B/mdb/m/mva-astn-form.html", Table: "mva-astn-20002421", task_name:"Motor Vehicle Accidents" },
        "wa-astn-data": { url: "$B/mdb/w/wa-astn-data.html", Table: "wa-astn-20002422", form_module: "wa-astn-form" },
        "wa-astn-form": { url: "$B/mdb/w/wa-astn-form.html", Table: "wa-astn-20002422", task_name:"Workplace_Accidents" },
        "than-you-astn-form": { url: "$B/mdb/t/than-you-astn-form.html" }
    }
    for (m in modules) { $vm.module_list[m] = modules[m]; }
})();
